/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImageVersion } from './commons-runner-image-version';

/**
 * 
 * @export
 * @interface CommonsListRunnerImageVersionsOutput
 */
export interface CommonsListRunnerImageVersionsOutput {
    /**
     * 
     * @type {Array<CommonsRunnerImageVersion>}
     * @memberof CommonsListRunnerImageVersionsOutput
     */
    'runner_image_versions'?: Array<CommonsRunnerImageVersion>;
}

