/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsWarpbuildSnapshotImage
 */
export interface CommonsWarpbuildSnapshotImage {
    /**
     * 
     * @type {string}
     * @memberof CommonsWarpbuildSnapshotImage
     */
    'creator_job_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsWarpbuildSnapshotImage
     */
    'creator_runner_instance_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsWarpbuildSnapshotImage
     */
    'provider'?: string;
    /**
     * SnapshotID is the ID of the snapshot.  +OutputOnly
     * @type {string}
     * @memberof CommonsWarpbuildSnapshotImage
     */
    'snapshot_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsWarpbuildSnapshotImage
     */
    'stack_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsWarpbuildSnapshotImage
     */
    'volume_id'?: string;
}

