/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonsContainerRunnerImageVersion } from './commons-container-runner-image-version';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImageVersionMeta } from './commons-runner-image-version-meta';

/**
 * 
 * @export
 * @interface CommonsRunnerImageVersion
 */
export interface CommonsRunnerImageVersion {
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'arch'?: string;
    /**
     * 
     * @type {CommonsContainerRunnerImageVersion}
     * @memberof CommonsRunnerImageVersion
     */
    'container_runner_image'?: CommonsContainerRunnerImageVersion;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'created_at'?: string;
    /**
     * ExternalID is the ID of the runner image version in the external system.
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'external_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'id'?: string;
    /**
     * 
     * @type {CommonsRunnerImageVersionMeta}
     * @memberof CommonsRunnerImageVersion
     */
    'meta'?: CommonsRunnerImageVersionMeta;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'organization_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'os'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'runner_image_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'runner_image_pull_secret_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImageVersion
     */
    'updated_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof CommonsRunnerImageVersion
     */
    'version_time_id'?: number;
}

