/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImagePullSecretAWS } from './commons-runner-image-pull-secret-aws';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImagePullSecretDockerCredentials } from './commons-runner-image-pull-secret-docker-credentials';

/**
 * 
 * @export
 * @interface CommonsRunnerImagePullSecret
 */
export interface CommonsRunnerImagePullSecret {
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImagePullSecret
     */
    'alias': string;
    /**
     * 
     * @type {CommonsRunnerImagePullSecretAWS}
     * @memberof CommonsRunnerImagePullSecret
     */
    'aws'?: CommonsRunnerImagePullSecretAWS;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImagePullSecret
     */
    'created_at': string;
    /**
     * 
     * @type {CommonsRunnerImagePullSecretDockerCredentials}
     * @memberof CommonsRunnerImagePullSecret
     */
    'docker_credentials'?: CommonsRunnerImagePullSecretDockerCredentials;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImagePullSecret
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImagePullSecret
     */
    'organization_id': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImagePullSecret
     */
    'type': CommonsRunnerImagePullSecretTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImagePullSecret
     */
    'updated_at': string;
}

export const CommonsRunnerImagePullSecretTypeEnum = {
    DockerCredentials: 'docker_credentials',
    Aws: 'aws'
} as const;

export type CommonsRunnerImagePullSecretTypeEnum = typeof CommonsRunnerImagePullSecretTypeEnum[keyof typeof CommonsRunnerImagePullSecretTypeEnum];


