/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsRunnerImageVersionMeta
 */
export interface CommonsRunnerImageVersionMeta {
    /**
     * 
     * @type {object}
     * @memberof CommonsRunnerImageVersionMeta
     */
    'event'?: object;
    /**
     * 
     * @type {object}
     * @memberof CommonsRunnerImageVersionMeta
     */
    'parsed_event'?: object;
}

