/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonsContainerRunnerImage } from './commons-container-runner-image';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImageHook } from './commons-runner-image-hook';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImageSettings } from './commons-runner-image-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsWarpbuildSnapshotImage } from './commons-warpbuild-snapshot-image';

/**
 * 
 * @export
 * @interface CommonsCreateRunnerImageInput
 */
export interface CommonsCreateRunnerImageInput {
    /**
     * 
     * @type {string}
     * @memberof CommonsCreateRunnerImageInput
     */
    'alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCreateRunnerImageInput
     */
    'arch'?: string;
    /**
     * 
     * @type {CommonsContainerRunnerImage}
     * @memberof CommonsCreateRunnerImageInput
     */
    'container_runner_image'?: CommonsContainerRunnerImage;
    /**
     * 
     * @type {Array<CommonsRunnerImageHook>}
     * @memberof CommonsCreateRunnerImageInput
     */
    'hooks'?: Array<CommonsRunnerImageHook>;
    /**
     * 
     * @type {string}
     * @memberof CommonsCreateRunnerImageInput
     */
    'os'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCreateRunnerImageInput
     */
    'runner_image_pull_secret_id'?: string;
    /**
     * 
     * @type {CommonsRunnerImageSettings}
     * @memberof CommonsCreateRunnerImageInput
     */
    'settings'?: CommonsRunnerImageSettings;
    /**
     * 
     * @type {string}
     * @memberof CommonsCreateRunnerImageInput
     */
    'type'?: string;
    /**
     * 
     * @type {CommonsWarpbuildSnapshotImage}
     * @memberof CommonsCreateRunnerImageInput
     */
    'warpbuild_snapshot_image'?: CommonsWarpbuildSnapshotImage;
}

