/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsRunnerImageSettings
 */
export interface CommonsRunnerImageSettings {
    /**
     * PurgeImageVersionsOffset is the number of versions to keep. Each time a new version is created, the oldest version is purged. Allowed values range [1, inf).  Default value is 2.
     * @type {number}
     * @memberof CommonsRunnerImageSettings
     */
    'purge_image_versions_offset'?: number;
}

