/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsRunnerImagePullSecretDockerCredentials
 */
export interface CommonsRunnerImagePullSecretDockerCredentials {
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImagePullSecretDockerCredentials
     */
    'host': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImagePullSecretDockerCredentials
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImagePullSecretDockerCredentials
     */
    'username': string;
}

