/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsRunnerImageHook
 */
export interface CommonsRunnerImageHook {
    /**
     * File is the base64 encoded file. This must be a shell script which is encoded in base64.
     * @type {string}
     * @memberof CommonsRunnerImageHook
     */
    'file'?: string;
    /**
     * Type is the type of hook.
     * @type {string}
     * @memberof CommonsRunnerImageHook
     */
    'type'?: CommonsRunnerImageHookTypeEnum;
}

export const CommonsRunnerImageHookTypeEnum = {
    Prehook: 'github_prehook',
    Posthook: 'github_posthook'
} as const;

export type CommonsRunnerImageHookTypeEnum = typeof CommonsRunnerImageHookTypeEnum[keyof typeof CommonsRunnerImageHookTypeEnum];


