/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsContainerRunnerImage
 */
export interface CommonsContainerRunnerImage {
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonsContainerRunnerImage
     */
    'args'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CommonsContainerRunnerImage
     */
    'command'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsContainerRunnerImage
     */
    'entrypoint'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommonsContainerRunnerImage
     */
    'environment_variables'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CommonsContainerRunnerImage
     */
    'image_repository'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsContainerRunnerImage
     */
    'image_tag'?: string;
}

