/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonsContainerRunnerImage } from './commons-container-runner-image';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImageHook } from './commons-runner-image-hook';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImageSettings } from './commons-runner-image-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsWarpbuildImage } from './commons-warpbuild-image';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsWarpbuildSnapshotImage } from './commons-warpbuild-snapshot-image';

/**
 * 
 * @export
 * @interface CommonsRunnerImage
 */
export interface CommonsRunnerImage {
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImage
     */
    'alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImage
     */
    'arch'?: string;
    /**
     * 
     * @type {CommonsContainerRunnerImage}
     * @memberof CommonsRunnerImage
     */
    'container_runner_image'?: CommonsContainerRunnerImage;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImage
     */
    'created_at'?: string;
    /**
     * 
     * @type {Array<CommonsRunnerImageHook>}
     * @memberof CommonsRunnerImage
     */
    'hooks'?: Array<CommonsRunnerImageHook>;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImage
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImage
     */
    'organization_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImage
     */
    'os'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImage
     */
    'runner_image_pull_secret_id'?: string;
    /**
     * 
     * @type {CommonsRunnerImageSettings}
     * @memberof CommonsRunnerImage
     */
    'settings'?: CommonsRunnerImageSettings;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImage
     */
    'status'?: CommonsRunnerImageStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImage
     */
    'type'?: CommonsRunnerImageTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CommonsRunnerImage
     */
    'updated_at'?: string;
    /**
     * 
     * @type {CommonsWarpbuildImage}
     * @memberof CommonsRunnerImage
     */
    'warpbuild_image'?: CommonsWarpbuildImage;
    /**
     * 
     * @type {CommonsWarpbuildSnapshotImage}
     * @memberof CommonsRunnerImage
     */
    'warpbuild_snapshot_image'?: CommonsWarpbuildSnapshotImage;
}

export const CommonsRunnerImageStatusEnum = {
    Creating: 'creating',
    Updating: 'updating',
    Deleting: 'deleting',
    Available: 'available',
    Failed: 'failed'
} as const;

export type CommonsRunnerImageStatusEnum = typeof CommonsRunnerImageStatusEnum[keyof typeof CommonsRunnerImageStatusEnum];
export const CommonsRunnerImageTypeEnum = {
    Container: 'container',
    WarpbuildManaged: 'warpbuild_managed'
} as const;

export type CommonsRunnerImageTypeEnum = typeof CommonsRunnerImageTypeEnum[keyof typeof CommonsRunnerImageTypeEnum];


