/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImagePullSecret } from './commons-runner-image-pull-secret';

/**
 * 
 * @export
 * @interface CommonsListRunnerImagePullSecretsOutput
 */
export interface CommonsListRunnerImagePullSecretsOutput {
    /**
     * 
     * @type {Array<CommonsRunnerImagePullSecret>}
     * @memberof CommonsListRunnerImagePullSecretsOutput
     */
    'runner_image_pull_secrets'?: Array<CommonsRunnerImagePullSecret>;
}

