/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImagePullSecretAWS } from './commons-runner-image-pull-secret-aws';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImagePullSecretDockerCredentials } from './commons-runner-image-pull-secret-docker-credentials';

/**
 * 
 * @export
 * @interface CommonsUpdateRunnerImagePullSecretInput
 */
export interface CommonsUpdateRunnerImagePullSecretInput {
    /**
     * 
     * @type {CommonsRunnerImagePullSecretAWS}
     * @memberof CommonsUpdateRunnerImagePullSecretInput
     */
    'aws'?: CommonsRunnerImagePullSecretAWS;
    /**
     * 
     * @type {CommonsRunnerImagePullSecretDockerCredentials}
     * @memberof CommonsUpdateRunnerImagePullSecretInput
     */
    'docker_credentials'?: CommonsRunnerImagePullSecretDockerCredentials;
}

