/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsUpdateContainerRunnerImageVersion
 */
export interface CommonsUpdateContainerRunnerImageVersion {
    /**
     * 
     * @type {string}
     * @memberof CommonsUpdateContainerRunnerImageVersion
     */
    'data_dir_size'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsUpdateContainerRunnerImageVersion
     */
    'image_digest'?: string;
    /**
     * ImageSize is the size of the image. Expected format: \"4G\"
     * @type {string}
     * @memberof CommonsUpdateContainerRunnerImageVersion
     */
    'image_size'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsUpdateContainerRunnerImageVersion
     */
    'snapshot_id'?: string;
    /**
     * SnapshotSize is the size of the snapshot in human readable format.
     * @type {string}
     * @memberof CommonsUpdateContainerRunnerImageVersion
     */
    'snapshot_size'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsUpdateContainerRunnerImageVersion
     */
    'volume_id'?: string;
    /**
     * VolumeSizeGB is the size of the volume in GB. This is used when creating a snapshot out of the volume.  This is rounded up to the nearest GiB.
     * @type {number}
     * @memberof CommonsUpdateContainerRunnerImageVersion
     */
    'volume_size_gb'?: number;
}

