/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonsContainerRunnerImageUpdate } from './commons-container-runner-image-update';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImageHook } from './commons-runner-image-hook';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsRunnerImageSettings } from './commons-runner-image-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonsWarpbuildSnapshotImage } from './commons-warpbuild-snapshot-image';

/**
 * 
 * @export
 * @interface CommonsUpdateRunnerImageInput
 */
export interface CommonsUpdateRunnerImageInput {
    /**
     * 
     * @type {CommonsContainerRunnerImageUpdate}
     * @memberof CommonsUpdateRunnerImageInput
     */
    'container_runner_image'?: CommonsContainerRunnerImageUpdate;
    /**
     * 
     * @type {Array<CommonsRunnerImageHook>}
     * @memberof CommonsUpdateRunnerImageInput
     */
    'hooks'?: Array<CommonsRunnerImageHook>;
    /**
     * 
     * @type {string}
     * @memberof CommonsUpdateRunnerImageInput
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsUpdateRunnerImageInput
     */
    'runner_image_pull_secret_id'?: string;
    /**
     * 
     * @type {CommonsRunnerImageSettings}
     * @memberof CommonsUpdateRunnerImageInput
     */
    'settings'?: CommonsRunnerImageSettings;
    /**
     * 
     * @type {CommonsWarpbuildSnapshotImage}
     * @memberof CommonsUpdateRunnerImageInput
     */
    'warpbuild_snapshot_image'?: CommonsWarpbuildSnapshotImage;
}

