name: 'snapshot-save'
description: 'Snapshot your volume and re-use it for faster builds'
author: 'WarpBuild'

inputs:
  warpbuild-base-url:
    description: 'Warpbuild Server base URL'
    required: false
  wait-timeout-minutes:
    description: 'Timeout in minutes to wait for the snapshot to be ready'
    required: false
    type: number
    default: 30
  alias:
    description: 'Alias for the snapshot'
    required: true
  fail-on-error:
    description: 'Fail the action if an error occurs'
    required: false
    default: 'true'

outputs: {}

runs:
  using: node20
  main: dist/index.js
