/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CommonsRunnerImageHook } from './CommonsRunnerImageHook'
import {
  CommonsRunnerImageHookFromJSON,
  CommonsRunnerImageHookFromJSONTyped,
  CommonsRunnerImageHookToJSON
} from './CommonsRunnerImageHook'
import type { CommonsWarpbuildImage } from './CommonsWarpbuildImage'
import {
  CommonsWarpbuildImageFromJSON,
  CommonsWarpbuildImageFromJSONTyped,
  CommonsWarpbuildImageToJSON
} from './CommonsWarpbuildImage'
import type { CommonsRunnerImageSettings } from './CommonsRunnerImageSettings'
import {
  CommonsRunnerImageSettingsFromJSON,
  CommonsRunnerImageSettingsFromJSONTyped,
  CommonsRunnerImageSettingsToJSON
} from './CommonsRunnerImageSettings'
import type { CommonsWarpbuildSnapshotImage } from './CommonsWarpbuildSnapshotImage'
import {
  CommonsWarpbuildSnapshotImageFromJSON,
  CommonsWarpbuildSnapshotImageFromJSONTyped,
  CommonsWarpbuildSnapshotImageToJSON
} from './CommonsWarpbuildSnapshotImage'
import type { CommonsContainerRunnerImage } from './CommonsContainerRunnerImage'
import {
  CommonsContainerRunnerImageFromJSON,
  CommonsContainerRunnerImageFromJSONTyped,
  CommonsContainerRunnerImageToJSON
} from './CommonsContainerRunnerImage'
import type { CommonsRunnerImageVersion } from './CommonsRunnerImageVersion'
import {
  CommonsRunnerImageVersionFromJSON,
  CommonsRunnerImageVersionFromJSONTyped,
  CommonsRunnerImageVersionToJSON
} from './CommonsRunnerImageVersion'

/**
 *
 * @export
 * @interface CommonsRunnerImage
 */
export interface CommonsRunnerImage {
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  alias?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  arch?: string
  /**
   *
   * @type {CommonsContainerRunnerImage}
   * @memberof CommonsRunnerImage
   */
  container_runner_image?: CommonsContainerRunnerImage
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  created_at?: string
  /**
   *
   * @type {Array<CommonsRunnerImageHook>}
   * @memberof CommonsRunnerImage
   */
  hooks?: Array<CommonsRunnerImageHook>
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  organization_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  os?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  parent_image_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  root_parent_image_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  runner_image_pull_secret_id?: string
  /**
   *
   * @type {CommonsRunnerImageSettings}
   * @memberof CommonsRunnerImage
   */
  settings?: CommonsRunnerImageSettings
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  stack_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  status?: CommonsRunnerImageStatusEnum
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  type?: CommonsRunnerImageTypeEnum
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImage
   */
  updated_at?: string
  /**
   *
   * @type {CommonsRunnerImageVersion}
   * @memberof CommonsRunnerImage
   */
  version?: CommonsRunnerImageVersion
  /**
   *
   * @type {CommonsWarpbuildImage}
   * @memberof CommonsRunnerImage
   */
  warpbuild_image?: CommonsWarpbuildImage
  /**
   *
   * @type {CommonsWarpbuildSnapshotImage}
   * @memberof CommonsRunnerImage
   */
  warpbuild_snapshot_image?: CommonsWarpbuildSnapshotImage
}

/**
 * @export
 */
export const CommonsRunnerImageStatusEnum = {
  creating: 'creating',
  updating: 'updating',
  deleting: 'deleting',
  available: 'available',
  failed: 'failed'
} as const
export type CommonsRunnerImageStatusEnum =
  (typeof CommonsRunnerImageStatusEnum)[keyof typeof CommonsRunnerImageStatusEnum]

/**
 * @export
 */
export const CommonsRunnerImageTypeEnum = {
  container: 'container',
  warpbuild_managed: 'warpbuild_managed',
  warpbuild_snapshot_image: 'warpbuild_snapshot_image'
} as const
export type CommonsRunnerImageTypeEnum =
  (typeof CommonsRunnerImageTypeEnum)[keyof typeof CommonsRunnerImageTypeEnum]

/**
 * Check if a given object implements the CommonsRunnerImage interface.
 */
export function instanceOfCommonsRunnerImage(
  value: object
): value is CommonsRunnerImage {
  if (!('id' in value) || value['id'] === undefined) return false
  return true
}

export function CommonsRunnerImageFromJSON(json: any): CommonsRunnerImage {
  return CommonsRunnerImageFromJSONTyped(json, false)
}

export function CommonsRunnerImageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsRunnerImage {
  if (json == null) {
    return json
  }
  return {
    alias: json['alias'] == null ? undefined : json['alias'],
    arch: json['arch'] == null ? undefined : json['arch'],
    container_runner_image:
      json['container_runner_image'] == null
        ? undefined
        : CommonsContainerRunnerImageFromJSON(json['container_runner_image']),
    created_at: json['created_at'] == null ? undefined : json['created_at'],
    hooks:
      json['hooks'] == null
        ? undefined
        : (json['hooks'] as Array<any>).map(CommonsRunnerImageHookFromJSON),
    id: json['id'],
    organization_id:
      json['organization_id'] == null ? undefined : json['organization_id'],
    os: json['os'] == null ? undefined : json['os'],
    parent_image_id:
      json['parent_image_id'] == null ? undefined : json['parent_image_id'],
    root_parent_image_id:
      json['root_parent_image_id'] == null
        ? undefined
        : json['root_parent_image_id'],
    runner_image_pull_secret_id:
      json['runner_image_pull_secret_id'] == null
        ? undefined
        : json['runner_image_pull_secret_id'],
    settings:
      json['settings'] == null
        ? undefined
        : CommonsRunnerImageSettingsFromJSON(json['settings']),
    stack_id: json['stack_id'] == null ? undefined : json['stack_id'],
    status: json['status'] == null ? undefined : json['status'],
    type: json['type'] == null ? undefined : json['type'],
    updated_at: json['updated_at'] == null ? undefined : json['updated_at'],
    version:
      json['version'] == null
        ? undefined
        : CommonsRunnerImageVersionFromJSON(json['version']),
    warpbuild_image:
      json['warpbuild_image'] == null
        ? undefined
        : CommonsWarpbuildImageFromJSON(json['warpbuild_image']),
    warpbuild_snapshot_image:
      json['warpbuild_snapshot_image'] == null
        ? undefined
        : CommonsWarpbuildSnapshotImageFromJSON(
            json['warpbuild_snapshot_image']
          )
  }
}

export function CommonsRunnerImageToJSON(
  value?: CommonsRunnerImage | null
): any {
  if (value == null) {
    return value
  }
  return {
    alias: value['alias'],
    arch: value['arch'],
    container_runner_image: CommonsContainerRunnerImageToJSON(
      value['container_runner_image']
    ),
    created_at: value['created_at'],
    hooks:
      value['hooks'] == null
        ? undefined
        : (value['hooks'] as Array<any>).map(CommonsRunnerImageHookToJSON),
    id: value['id'],
    organization_id: value['organization_id'],
    os: value['os'],
    parent_image_id: value['parent_image_id'],
    root_parent_image_id: value['root_parent_image_id'],
    runner_image_pull_secret_id: value['runner_image_pull_secret_id'],
    settings: CommonsRunnerImageSettingsToJSON(value['settings']),
    stack_id: value['stack_id'],
    status: value['status'],
    type: value['type'],
    updated_at: value['updated_at'],
    version: CommonsRunnerImageVersionToJSON(value['version']),
    warpbuild_image: CommonsWarpbuildImageToJSON(value['warpbuild_image']),
    warpbuild_snapshot_image: CommonsWarpbuildSnapshotImageToJSON(
      value['warpbuild_snapshot_image']
    )
  }
}
