/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CommonsContainerRunnerImage
 */
export interface CommonsContainerRunnerImage {
  /**
   *
   * @type {Array<string>}
   * @memberof CommonsContainerRunnerImage
   */
  args?: Array<string>
  /**
   *
   * @type {string}
   * @memberof CommonsContainerRunnerImage
   */
  command?: string
  /**
   *
   * @type {string}
   * @memberof CommonsContainerRunnerImage
   */
  entrypoint?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof CommonsContainerRunnerImage
   */
  environment_variables?: { [key: string]: string }
  /**
   *
   * @type {string}
   * @memberof CommonsContainerRunnerImage
   */
  image_repository?: string
  /**
   *
   * @type {string}
   * @memberof CommonsContainerRunnerImage
   */
  image_tag?: string
}

/**
 * Check if a given object implements the CommonsContainerRunnerImage interface.
 */
export function instanceOfCommonsContainerRunnerImage(
  value: object
): value is CommonsContainerRunnerImage {
  return true
}

export function CommonsContainerRunnerImageFromJSON(
  json: any
): CommonsContainerRunnerImage {
  return CommonsContainerRunnerImageFromJSONTyped(json, false)
}

export function CommonsContainerRunnerImageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsContainerRunnerImage {
  if (json == null) {
    return json
  }
  return {
    args: json['args'] == null ? undefined : json['args'],
    command: json['command'] == null ? undefined : json['command'],
    entrypoint: json['entrypoint'] == null ? undefined : json['entrypoint'],
    environment_variables:
      json['environment_variables'] == null
        ? undefined
        : json['environment_variables'],
    image_repository:
      json['image_repository'] == null ? undefined : json['image_repository'],
    image_tag: json['image_tag'] == null ? undefined : json['image_tag']
  }
}

export function CommonsContainerRunnerImageToJSON(
  value?: CommonsContainerRunnerImage | null
): any {
  if (value == null) {
    return value
  }
  return {
    args: value['args'],
    command: value['command'],
    entrypoint: value['entrypoint'],
    environment_variables: value['environment_variables'],
    image_repository: value['image_repository'],
    image_tag: value['image_tag']
  }
}
