/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CommonsContainerRunnerImageUpdate
 */
export interface CommonsContainerRunnerImageUpdate {
  /**
   *
   * @type {string}
   * @memberof CommonsContainerRunnerImageUpdate
   */
  image_tag?: string
}

/**
 * Check if a given object implements the CommonsContainerRunnerImageUpdate interface.
 */
export function instanceOfCommonsContainerRunnerImageUpdate(
  value: object
): value is CommonsContainerRunnerImageUpdate {
  return true
}

export function CommonsContainerRunnerImageUpdateFromJSON(
  json: any
): CommonsContainerRunnerImageUpdate {
  return CommonsContainerRunnerImageUpdateFromJSONTyped(json, false)
}

export function CommonsContainerRunnerImageUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsContainerRunnerImageUpdate {
  if (json == null) {
    return json
  }
  return {
    image_tag: json['image_tag'] == null ? undefined : json['image_tag']
  }
}

export function CommonsContainerRunnerImageUpdateToJSON(
  value?: CommonsContainerRunnerImageUpdate | null
): any {
  if (value == null) {
    return value
  }
  return {
    image_tag: value['image_tag']
  }
}
