/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CommonsUpdateContainerRunnerImageVersion
 */
export interface CommonsUpdateContainerRunnerImageVersion {
  /**
   *
   * @type {string}
   * @memberof CommonsUpdateContainerRunnerImageVersion
   */
  data_dir_size?: string
  /**
   *
   * @type {string}
   * @memberof CommonsUpdateContainerRunnerImageVersion
   */
  image_digest?: string
  /**
   * ImageSize is the size of the image.
   * Expected format: "4G"
   * @type {string}
   * @memberof CommonsUpdateContainerRunnerImageVersion
   */
  image_size?: string
  /**
   *
   * @type {string}
   * @memberof CommonsUpdateContainerRunnerImageVersion
   */
  snapshot_id?: string
  /**
   * SnapshotSize is the size of the snapshot in human readable format.
   * @type {string}
   * @memberof CommonsUpdateContainerRunnerImageVersion
   */
  snapshot_size?: string
  /**
   *
   * @type {string}
   * @memberof CommonsUpdateContainerRunnerImageVersion
   */
  volume_id?: string
  /**
   * VolumeSizeGB is the size of the volume in GB.
   * This is used when creating a snapshot out of the volume.
   *
   * This is rounded up to the nearest GiB.
   * @type {number}
   * @memberof CommonsUpdateContainerRunnerImageVersion
   */
  volume_size_gb?: number
}

/**
 * Check if a given object implements the CommonsUpdateContainerRunnerImageVersion interface.
 */
export function instanceOfCommonsUpdateContainerRunnerImageVersion(
  value: object
): value is CommonsUpdateContainerRunnerImageVersion {
  return true
}

export function CommonsUpdateContainerRunnerImageVersionFromJSON(
  json: any
): CommonsUpdateContainerRunnerImageVersion {
  return CommonsUpdateContainerRunnerImageVersionFromJSONTyped(json, false)
}

export function CommonsUpdateContainerRunnerImageVersionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsUpdateContainerRunnerImageVersion {
  if (json == null) {
    return json
  }
  return {
    data_dir_size:
      json['data_dir_size'] == null ? undefined : json['data_dir_size'],
    image_digest:
      json['image_digest'] == null ? undefined : json['image_digest'],
    image_size: json['image_size'] == null ? undefined : json['image_size'],
    snapshot_id: json['snapshot_id'] == null ? undefined : json['snapshot_id'],
    snapshot_size:
      json['snapshot_size'] == null ? undefined : json['snapshot_size'],
    volume_id: json['volume_id'] == null ? undefined : json['volume_id'],
    volume_size_gb:
      json['volume_size_gb'] == null ? undefined : json['volume_size_gb']
  }
}

export function CommonsUpdateContainerRunnerImageVersionToJSON(
  value?: CommonsUpdateContainerRunnerImageVersion | null
): any {
  if (value == null) {
    return value
  }
  return {
    data_dir_size: value['data_dir_size'],
    image_digest: value['image_digest'],
    image_size: value['image_size'],
    snapshot_id: value['snapshot_id'],
    snapshot_size: value['snapshot_size'],
    volume_id: value['volume_id'],
    volume_size_gb: value['volume_size_gb']
  }
}
