/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CommonsWarpbuildSnapshotImage
 */
export interface CommonsWarpbuildSnapshotImage {
  /**
   * AMIID is the ID of the AMI.
   *
   * +OutputOnly
   * @type {string}
   * @memberof CommonsWarpbuildSnapshotImage
   */
  ami_id?: string
  /**
   * CreatorRunnerInstanceID is the ID of the runner instance that created the snapshot.
   * This is populated via the auth token.
   *
   * +OutputOnly
   * @type {string}
   * @memberof CommonsWarpbuildSnapshotImage
   */
  creator_runner_instance_id?: string
  /**
   * Provider is the cloud provider of the snapshot.
   *
   * +OutputOnly
   * @type {string}
   * @memberof CommonsWarpbuildSnapshotImage
   */
  provider?: string
  /**
   * SnapshotID is the ID of the snapshot.
   *
   * +OutputOnly
   * @type {string}
   * @memberof CommonsWarpbuildSnapshotImage
   */
  snapshot_id?: string
  /**
   * VCSOrganizationName is the name of the VCS organization.
   * This is populated via the auth token.
   *
   * +OutputOnly
   * @type {string}
   * @memberof CommonsWarpbuildSnapshotImage
   */
  vcs_organization_name?: string
  /**
   * VCSRepositoryName is the name of the VCS repository.
   * This is populated via the auth token.
   *
   * +OutputOnly
   * @type {string}
   * @memberof CommonsWarpbuildSnapshotImage
   */
  vcs_repository_name?: string
}

/**
 * Check if a given object implements the CommonsWarpbuildSnapshotImage interface.
 */
export function instanceOfCommonsWarpbuildSnapshotImage(
  value: object
): value is CommonsWarpbuildSnapshotImage {
  return true
}

export function CommonsWarpbuildSnapshotImageFromJSON(
  json: any
): CommonsWarpbuildSnapshotImage {
  return CommonsWarpbuildSnapshotImageFromJSONTyped(json, false)
}

export function CommonsWarpbuildSnapshotImageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsWarpbuildSnapshotImage {
  if (json == null) {
    return json
  }
  return {
    ami_id: json['ami_id'] == null ? undefined : json['ami_id'],
    creator_runner_instance_id:
      json['creator_runner_instance_id'] == null
        ? undefined
        : json['creator_runner_instance_id'],
    provider: json['provider'] == null ? undefined : json['provider'],
    snapshot_id: json['snapshot_id'] == null ? undefined : json['snapshot_id'],
    vcs_organization_name:
      json['vcs_organization_name'] == null
        ? undefined
        : json['vcs_organization_name'],
    vcs_repository_name:
      json['vcs_repository_name'] == null
        ? undefined
        : json['vcs_repository_name']
  }
}

export function CommonsWarpbuildSnapshotImageToJSON(
  value?: CommonsWarpbuildSnapshotImage | null
): any {
  if (value == null) {
    return value
  }
  return {
    ami_id: value['ami_id'],
    creator_runner_instance_id: value['creator_runner_instance_id'],
    provider: value['provider'],
    snapshot_id: value['snapshot_id'],
    vcs_organization_name: value['vcs_organization_name'],
    vcs_repository_name: value['vcs_repository_name']
  }
}
