/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CommonsRunnerImageVersion } from './CommonsRunnerImageVersion'
import {
  CommonsRunnerImageVersionFromJSON,
  CommonsRunnerImageVersionFromJSONTyped,
  CommonsRunnerImageVersionToJSON
} from './CommonsRunnerImageVersion'

/**
 *
 * @export
 * @interface CommonsListRunnerImageVersionsOutput
 */
export interface CommonsListRunnerImageVersionsOutput {
  /**
   *
   * @type {Array<CommonsRunnerImageVersion>}
   * @memberof CommonsListRunnerImageVersionsOutput
   */
  runner_image_versions?: Array<CommonsRunnerImageVersion>
}

/**
 * Check if a given object implements the CommonsListRunnerImageVersionsOutput interface.
 */
export function instanceOfCommonsListRunnerImageVersionsOutput(
  value: object
): value is CommonsListRunnerImageVersionsOutput {
  return true
}

export function CommonsListRunnerImageVersionsOutputFromJSON(
  json: any
): CommonsListRunnerImageVersionsOutput {
  return CommonsListRunnerImageVersionsOutputFromJSONTyped(json, false)
}

export function CommonsListRunnerImageVersionsOutputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsListRunnerImageVersionsOutput {
  if (json == null) {
    return json
  }
  return {
    runner_image_versions:
      json['runner_image_versions'] == null
        ? undefined
        : (json['runner_image_versions'] as Array<any>).map(
            CommonsRunnerImageVersionFromJSON
          )
  }
}

export function CommonsListRunnerImageVersionsOutputToJSON(
  value?: CommonsListRunnerImageVersionsOutput | null
): any {
  if (value == null) {
    return value
  }
  return {
    runner_image_versions:
      value['runner_image_versions'] == null
        ? undefined
        : (value['runner_image_versions'] as Array<any>).map(
            CommonsRunnerImageVersionToJSON
          )
  }
}
