/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CommonsUpdateContainerRunnerImageVersion } from './CommonsUpdateContainerRunnerImageVersion'
import {
  CommonsUpdateContainerRunnerImageVersionFromJSON,
  CommonsUpdateContainerRunnerImageVersionFromJSONTyped,
  CommonsUpdateContainerRunnerImageVersionToJSON
} from './CommonsUpdateContainerRunnerImageVersion'
import type { CommonsWarpbuildSnapshotImage } from './CommonsWarpbuildSnapshotImage'
import {
  CommonsWarpbuildSnapshotImageFromJSON,
  CommonsWarpbuildSnapshotImageFromJSONTyped,
  CommonsWarpbuildSnapshotImageToJSON
} from './CommonsWarpbuildSnapshotImage'

/**
 *
 * @export
 * @interface CommonsUpdateRunnerImageVersionInput
 */
export interface CommonsUpdateRunnerImageVersionInput {
  /**
   *
   * @type {CommonsUpdateContainerRunnerImageVersion}
   * @memberof CommonsUpdateRunnerImageVersionInput
   */
  container_runner_image_version?: CommonsUpdateContainerRunnerImageVersion
  /**
   *
   * @type {string}
   * @memberof CommonsUpdateRunnerImageVersionInput
   */
  parent_image_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsUpdateRunnerImageVersionInput
   */
  status?: string
  /**
   *
   * @type {CommonsWarpbuildSnapshotImage}
   * @memberof CommonsUpdateRunnerImageVersionInput
   */
  warpbuild_snapshot_image?: CommonsWarpbuildSnapshotImage
}

/**
 * Check if a given object implements the CommonsUpdateRunnerImageVersionInput interface.
 */
export function instanceOfCommonsUpdateRunnerImageVersionInput(
  value: object
): value is CommonsUpdateRunnerImageVersionInput {
  return true
}

export function CommonsUpdateRunnerImageVersionInputFromJSON(
  json: any
): CommonsUpdateRunnerImageVersionInput {
  return CommonsUpdateRunnerImageVersionInputFromJSONTyped(json, false)
}

export function CommonsUpdateRunnerImageVersionInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsUpdateRunnerImageVersionInput {
  if (json == null) {
    return json
  }
  return {
    container_runner_image_version:
      json['container_runner_image_version'] == null
        ? undefined
        : CommonsUpdateContainerRunnerImageVersionFromJSON(
            json['container_runner_image_version']
          ),
    parent_image_id:
      json['parent_image_id'] == null ? undefined : json['parent_image_id'],
    status: json['status'] == null ? undefined : json['status'],
    warpbuild_snapshot_image:
      json['warpbuild_snapshot_image'] == null
        ? undefined
        : CommonsWarpbuildSnapshotImageFromJSON(
            json['warpbuild_snapshot_image']
          )
  }
}

export function CommonsUpdateRunnerImageVersionInputToJSON(
  value?: CommonsUpdateRunnerImageVersionInput | null
): any {
  if (value == null) {
    return value
  }
  return {
    container_runner_image_version:
      CommonsUpdateContainerRunnerImageVersionToJSON(
        value['container_runner_image_version']
      ),
    parent_image_id: value['parent_image_id'],
    status: value['status'],
    warpbuild_snapshot_image: CommonsWarpbuildSnapshotImageToJSON(
      value['warpbuild_snapshot_image']
    )
  }
}
