/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CommonsRunnerImageHook } from './CommonsRunnerImageHook'
import {
  CommonsRunnerImageHookFromJSON,
  CommonsRunnerImageHookFromJSONTyped,
  CommonsRunnerImageHookToJSON
} from './CommonsRunnerImageHook'
import type { CommonsRunnerImageSettings } from './CommonsRunnerImageSettings'
import {
  CommonsRunnerImageSettingsFromJSON,
  CommonsRunnerImageSettingsFromJSONTyped,
  CommonsRunnerImageSettingsToJSON
} from './CommonsRunnerImageSettings'
import type { CommonsWarpbuildSnapshotImage } from './CommonsWarpbuildSnapshotImage'
import {
  CommonsWarpbuildSnapshotImageFromJSON,
  CommonsWarpbuildSnapshotImageFromJSONTyped,
  CommonsWarpbuildSnapshotImageToJSON
} from './CommonsWarpbuildSnapshotImage'
import type { CommonsContainerRunnerImage } from './CommonsContainerRunnerImage'
import {
  CommonsContainerRunnerImageFromJSON,
  CommonsContainerRunnerImageFromJSONTyped,
  CommonsContainerRunnerImageToJSON
} from './CommonsContainerRunnerImage'

/**
 *
 * @export
 * @interface CommonsCreateRunnerImageInput
 */
export interface CommonsCreateRunnerImageInput {
  /**
   *
   * @type {string}
   * @memberof CommonsCreateRunnerImageInput
   */
  alias?: string
  /**
   *
   * @type {string}
   * @memberof CommonsCreateRunnerImageInput
   */
  arch?: string
  /**
   *
   * @type {CommonsContainerRunnerImage}
   * @memberof CommonsCreateRunnerImageInput
   */
  container_runner_image?: CommonsContainerRunnerImage
  /**
   *
   * @type {Array<CommonsRunnerImageHook>}
   * @memberof CommonsCreateRunnerImageInput
   */
  hooks?: Array<CommonsRunnerImageHook>
  /**
   *
   * @type {string}
   * @memberof CommonsCreateRunnerImageInput
   */
  os?: string
  /**
   *
   * @type {string}
   * @memberof CommonsCreateRunnerImageInput
   */
  runner_image_pull_secret_id?: string
  /**
   *
   * @type {CommonsRunnerImageSettings}
   * @memberof CommonsCreateRunnerImageInput
   */
  settings?: CommonsRunnerImageSettings
  /**
   *
   * @type {string}
   * @memberof CommonsCreateRunnerImageInput
   */
  stack_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsCreateRunnerImageInput
   */
  type?: string
  /**
   *
   * @type {CommonsWarpbuildSnapshotImage}
   * @memberof CommonsCreateRunnerImageInput
   */
  warpbuild_snapshot_image?: CommonsWarpbuildSnapshotImage
}

/**
 * Check if a given object implements the CommonsCreateRunnerImageInput interface.
 */
export function instanceOfCommonsCreateRunnerImageInput(
  value: object
): value is CommonsCreateRunnerImageInput {
  return true
}

export function CommonsCreateRunnerImageInputFromJSON(
  json: any
): CommonsCreateRunnerImageInput {
  return CommonsCreateRunnerImageInputFromJSONTyped(json, false)
}

export function CommonsCreateRunnerImageInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsCreateRunnerImageInput {
  if (json == null) {
    return json
  }
  return {
    alias: json['alias'] == null ? undefined : json['alias'],
    arch: json['arch'] == null ? undefined : json['arch'],
    container_runner_image:
      json['container_runner_image'] == null
        ? undefined
        : CommonsContainerRunnerImageFromJSON(json['container_runner_image']),
    hooks:
      json['hooks'] == null
        ? undefined
        : (json['hooks'] as Array<any>).map(CommonsRunnerImageHookFromJSON),
    os: json['os'] == null ? undefined : json['os'],
    runner_image_pull_secret_id:
      json['runner_image_pull_secret_id'] == null
        ? undefined
        : json['runner_image_pull_secret_id'],
    settings:
      json['settings'] == null
        ? undefined
        : CommonsRunnerImageSettingsFromJSON(json['settings']),
    stack_id: json['stack_id'] == null ? undefined : json['stack_id'],
    type: json['type'] == null ? undefined : json['type'],
    warpbuild_snapshot_image:
      json['warpbuild_snapshot_image'] == null
        ? undefined
        : CommonsWarpbuildSnapshotImageFromJSON(
            json['warpbuild_snapshot_image']
          )
  }
}

export function CommonsCreateRunnerImageInputToJSON(
  value?: CommonsCreateRunnerImageInput | null
): any {
  if (value == null) {
    return value
  }
  return {
    alias: value['alias'],
    arch: value['arch'],
    container_runner_image: CommonsContainerRunnerImageToJSON(
      value['container_runner_image']
    ),
    hooks:
      value['hooks'] == null
        ? undefined
        : (value['hooks'] as Array<any>).map(CommonsRunnerImageHookToJSON),
    os: value['os'],
    runner_image_pull_secret_id: value['runner_image_pull_secret_id'],
    settings: CommonsRunnerImageSettingsToJSON(value['settings']),
    stack_id: value['stack_id'],
    type: value['type'],
    warpbuild_snapshot_image: CommonsWarpbuildSnapshotImageToJSON(
      value['warpbuild_snapshot_image']
    )
  }
}
