/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CommonsRunnerImageVersionMeta
 */
export interface CommonsRunnerImageVersionMeta {
  /**
   *
   * @type {object}
   * @memberof CommonsRunnerImageVersionMeta
   */
  event?: object
  /**
   *
   * @type {object}
   * @memberof CommonsRunnerImageVersionMeta
   */
  parsed_event?: object
}

/**
 * Check if a given object implements the CommonsRunnerImageVersionMeta interface.
 */
export function instanceOfCommonsRunnerImageVersionMeta(
  value: object
): value is CommonsRunnerImageVersionMeta {
  return true
}

export function CommonsRunnerImageVersionMetaFromJSON(
  json: any
): CommonsRunnerImageVersionMeta {
  return CommonsRunnerImageVersionMetaFromJSONTyped(json, false)
}

export function CommonsRunnerImageVersionMetaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsRunnerImageVersionMeta {
  if (json == null) {
    return json
  }
  return {
    event: json['event'] == null ? undefined : json['event'],
    parsed_event:
      json['parsed_event'] == null ? undefined : json['parsed_event']
  }
}

export function CommonsRunnerImageVersionMetaToJSON(
  value?: CommonsRunnerImageVersionMeta | null
): any {
  if (value == null) {
    return value
  }
  return {
    event: value['event'],
    parsed_event: value['parsed_event']
  }
}
