/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CommonsRunnerImagePullSecretDockerCredentials } from './CommonsRunnerImagePullSecretDockerCredentials'
import {
  CommonsRunnerImagePullSecretDockerCredentialsFromJSON,
  CommonsRunnerImagePullSecretDockerCredentialsFromJSONTyped,
  CommonsRunnerImagePullSecretDockerCredentialsToJSON
} from './CommonsRunnerImagePullSecretDockerCredentials'
import type { CommonsRunnerImagePullSecretAWS } from './CommonsRunnerImagePullSecretAWS'
import {
  CommonsRunnerImagePullSecretAWSFromJSON,
  CommonsRunnerImagePullSecretAWSFromJSONTyped,
  CommonsRunnerImagePullSecretAWSToJSON
} from './CommonsRunnerImagePullSecretAWS'

/**
 *
 * @export
 * @interface CommonsCreateRunnerImagePullSecretInput
 */
export interface CommonsCreateRunnerImagePullSecretInput {
  /**
   *
   * @type {string}
   * @memberof CommonsCreateRunnerImagePullSecretInput
   */
  alias: string
  /**
   *
   * @type {CommonsRunnerImagePullSecretAWS}
   * @memberof CommonsCreateRunnerImagePullSecretInput
   */
  aws?: CommonsRunnerImagePullSecretAWS
  /**
   *
   * @type {CommonsRunnerImagePullSecretDockerCredentials}
   * @memberof CommonsCreateRunnerImagePullSecretInput
   */
  docker_credentials?: CommonsRunnerImagePullSecretDockerCredentials
  /**
   *
   * @type {string}
   * @memberof CommonsCreateRunnerImagePullSecretInput
   */
  type: CommonsCreateRunnerImagePullSecretInputTypeEnum
}

/**
 * @export
 */
export const CommonsCreateRunnerImagePullSecretInputTypeEnum = {
  docker_credentials: 'docker_credentials',
  aws: 'aws'
} as const
export type CommonsCreateRunnerImagePullSecretInputTypeEnum =
  (typeof CommonsCreateRunnerImagePullSecretInputTypeEnum)[keyof typeof CommonsCreateRunnerImagePullSecretInputTypeEnum]

/**
 * Check if a given object implements the CommonsCreateRunnerImagePullSecretInput interface.
 */
export function instanceOfCommonsCreateRunnerImagePullSecretInput(
  value: object
): value is CommonsCreateRunnerImagePullSecretInput {
  if (!('alias' in value) || value['alias'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function CommonsCreateRunnerImagePullSecretInputFromJSON(
  json: any
): CommonsCreateRunnerImagePullSecretInput {
  return CommonsCreateRunnerImagePullSecretInputFromJSONTyped(json, false)
}

export function CommonsCreateRunnerImagePullSecretInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsCreateRunnerImagePullSecretInput {
  if (json == null) {
    return json
  }
  return {
    alias: json['alias'],
    aws:
      json['aws'] == null
        ? undefined
        : CommonsRunnerImagePullSecretAWSFromJSON(json['aws']),
    docker_credentials:
      json['docker_credentials'] == null
        ? undefined
        : CommonsRunnerImagePullSecretDockerCredentialsFromJSON(
            json['docker_credentials']
          ),
    type: json['type']
  }
}

export function CommonsCreateRunnerImagePullSecretInputToJSON(
  value?: CommonsCreateRunnerImagePullSecretInput | null
): any {
  if (value == null) {
    return value
  }
  return {
    alias: value['alias'],
    aws: CommonsRunnerImagePullSecretAWSToJSON(value['aws']),
    docker_credentials: CommonsRunnerImagePullSecretDockerCredentialsToJSON(
      value['docker_credentials']
    ),
    type: value['type']
  }
}
