/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CommonsRunnerImageHook } from './CommonsRunnerImageHook'
import {
  CommonsRunnerImageHookFromJSON,
  CommonsRunnerImageHookFromJSONTyped,
  CommonsRunnerImageHookToJSON
} from './CommonsRunnerImageHook'
import type { CommonsContainerRunnerImageUpdate } from './CommonsContainerRunnerImageUpdate'
import {
  CommonsContainerRunnerImageUpdateFromJSON,
  CommonsContainerRunnerImageUpdateFromJSONTyped,
  CommonsContainerRunnerImageUpdateToJSON
} from './CommonsContainerRunnerImageUpdate'
import type { CommonsRunnerImageSettings } from './CommonsRunnerImageSettings'
import {
  CommonsRunnerImageSettingsFromJSON,
  CommonsRunnerImageSettingsFromJSONTyped,
  CommonsRunnerImageSettingsToJSON
} from './CommonsRunnerImageSettings'
import type { CommonsWarpbuildSnapshotImage } from './CommonsWarpbuildSnapshotImage'
import {
  CommonsWarpbuildSnapshotImageFromJSON,
  CommonsWarpbuildSnapshotImageFromJSONTyped,
  CommonsWarpbuildSnapshotImageToJSON
} from './CommonsWarpbuildSnapshotImage'

/**
 *
 * @export
 * @interface CommonsUpdateRunnerImageInput
 */
export interface CommonsUpdateRunnerImageInput {
  /**
   *
   * @type {CommonsContainerRunnerImageUpdate}
   * @memberof CommonsUpdateRunnerImageInput
   */
  container_runner_image?: CommonsContainerRunnerImageUpdate
  /**
   *
   * @type {Array<CommonsRunnerImageHook>}
   * @memberof CommonsUpdateRunnerImageInput
   */
  hooks?: Array<CommonsRunnerImageHook>
  /**
   *
   * @type {string}
   * @memberof CommonsUpdateRunnerImageInput
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsUpdateRunnerImageInput
   */
  runner_image_pull_secret_id?: string
  /**
   *
   * @type {CommonsRunnerImageSettings}
   * @memberof CommonsUpdateRunnerImageInput
   */
  settings?: CommonsRunnerImageSettings
  /**
   *
   * @type {CommonsWarpbuildSnapshotImage}
   * @memberof CommonsUpdateRunnerImageInput
   */
  warpbuild_snapshot_image?: CommonsWarpbuildSnapshotImage
}

/**
 * Check if a given object implements the CommonsUpdateRunnerImageInput interface.
 */
export function instanceOfCommonsUpdateRunnerImageInput(
  value: object
): value is CommonsUpdateRunnerImageInput {
  return true
}

export function CommonsUpdateRunnerImageInputFromJSON(
  json: any
): CommonsUpdateRunnerImageInput {
  return CommonsUpdateRunnerImageInputFromJSONTyped(json, false)
}

export function CommonsUpdateRunnerImageInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsUpdateRunnerImageInput {
  if (json == null) {
    return json
  }
  return {
    container_runner_image:
      json['container_runner_image'] == null
        ? undefined
        : CommonsContainerRunnerImageUpdateFromJSON(
            json['container_runner_image']
          ),
    hooks:
      json['hooks'] == null
        ? undefined
        : (json['hooks'] as Array<any>).map(CommonsRunnerImageHookFromJSON),
    id: json['id'] == null ? undefined : json['id'],
    runner_image_pull_secret_id:
      json['runner_image_pull_secret_id'] == null
        ? undefined
        : json['runner_image_pull_secret_id'],
    settings:
      json['settings'] == null
        ? undefined
        : CommonsRunnerImageSettingsFromJSON(json['settings']),
    warpbuild_snapshot_image:
      json['warpbuild_snapshot_image'] == null
        ? undefined
        : CommonsWarpbuildSnapshotImageFromJSON(
            json['warpbuild_snapshot_image']
          )
  }
}

export function CommonsUpdateRunnerImageInputToJSON(
  value?: CommonsUpdateRunnerImageInput | null
): any {
  if (value == null) {
    return value
  }
  return {
    container_runner_image: CommonsContainerRunnerImageUpdateToJSON(
      value['container_runner_image']
    ),
    hooks:
      value['hooks'] == null
        ? undefined
        : (value['hooks'] as Array<any>).map(CommonsRunnerImageHookToJSON),
    id: value['id'],
    runner_image_pull_secret_id: value['runner_image_pull_secret_id'],
    settings: CommonsRunnerImageSettingsToJSON(value['settings']),
    warpbuild_snapshot_image: CommonsWarpbuildSnapshotImageToJSON(
      value['warpbuild_snapshot_image']
    )
  }
}
