/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CommonsContainerRunnerImageVersion } from './CommonsContainerRunnerImageVersion'
import {
  CommonsContainerRunnerImageVersionFromJSON,
  CommonsContainerRunnerImageVersionFromJSONTyped,
  CommonsContainerRunnerImageVersionToJSON
} from './CommonsContainerRunnerImageVersion'
import type { CommonsRunnerImageVersionMeta } from './CommonsRunnerImageVersionMeta'
import {
  CommonsRunnerImageVersionMetaFromJSON,
  CommonsRunnerImageVersionMetaFromJSONTyped,
  CommonsRunnerImageVersionMetaToJSON
} from './CommonsRunnerImageVersionMeta'

/**
 *
 * @export
 * @interface CommonsRunnerImageVersion
 */
export interface CommonsRunnerImageVersion {
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  arch?: string
  /**
   *
   * @type {CommonsContainerRunnerImageVersion}
   * @memberof CommonsRunnerImageVersion
   */
  container_runner_image?: CommonsContainerRunnerImageVersion
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  created_at?: string
  /**
   * ExternalID is the ID of the runner image version in the external system.
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  external_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  id?: string
  /**
   *
   * @type {CommonsRunnerImageVersionMeta}
   * @memberof CommonsRunnerImageVersion
   */
  meta?: CommonsRunnerImageVersionMeta
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  organization_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  os?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  runner_image_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  runner_image_pull_secret_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  stack_id?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  status?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  type?: string
  /**
   *
   * @type {string}
   * @memberof CommonsRunnerImageVersion
   */
  updated_at?: string
  /**
   *
   * @type {number}
   * @memberof CommonsRunnerImageVersion
   */
  version_time_id?: number
}

/**
 * Check if a given object implements the CommonsRunnerImageVersion interface.
 */
export function instanceOfCommonsRunnerImageVersion(
  value: object
): value is CommonsRunnerImageVersion {
  return true
}

export function CommonsRunnerImageVersionFromJSON(
  json: any
): CommonsRunnerImageVersion {
  return CommonsRunnerImageVersionFromJSONTyped(json, false)
}

export function CommonsRunnerImageVersionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsRunnerImageVersion {
  if (json == null) {
    return json
  }
  return {
    arch: json['arch'] == null ? undefined : json['arch'],
    container_runner_image:
      json['container_runner_image'] == null
        ? undefined
        : CommonsContainerRunnerImageVersionFromJSON(
            json['container_runner_image']
          ),
    created_at: json['created_at'] == null ? undefined : json['created_at'],
    external_id: json['external_id'] == null ? undefined : json['external_id'],
    id: json['id'] == null ? undefined : json['id'],
    meta:
      json['meta'] == null
        ? undefined
        : CommonsRunnerImageVersionMetaFromJSON(json['meta']),
    organization_id:
      json['organization_id'] == null ? undefined : json['organization_id'],
    os: json['os'] == null ? undefined : json['os'],
    runner_image_id:
      json['runner_image_id'] == null ? undefined : json['runner_image_id'],
    runner_image_pull_secret_id:
      json['runner_image_pull_secret_id'] == null
        ? undefined
        : json['runner_image_pull_secret_id'],
    stack_id: json['stack_id'] == null ? undefined : json['stack_id'],
    status: json['status'] == null ? undefined : json['status'],
    type: json['type'] == null ? undefined : json['type'],
    updated_at: json['updated_at'] == null ? undefined : json['updated_at'],
    version_time_id:
      json['version_time_id'] == null ? undefined : json['version_time_id']
  }
}

export function CommonsRunnerImageVersionToJSON(
  value?: CommonsRunnerImageVersion | null
): any {
  if (value == null) {
    return value
  }
  return {
    arch: value['arch'],
    container_runner_image: CommonsContainerRunnerImageVersionToJSON(
      value['container_runner_image']
    ),
    created_at: value['created_at'],
    external_id: value['external_id'],
    id: value['id'],
    meta: CommonsRunnerImageVersionMetaToJSON(value['meta']),
    organization_id: value['organization_id'],
    os: value['os'],
    runner_image_id: value['runner_image_id'],
    runner_image_pull_secret_id: value['runner_image_pull_secret_id'],
    stack_id: value['stack_id'],
    status: value['status'],
    type: value['type'],
    updated_at: value['updated_at'],
    version_time_id: value['version_time_id']
  }
}
