/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CommonsRunnerImagePullSecret } from './CommonsRunnerImagePullSecret'
import {
  CommonsRunnerImagePullSecretFromJSON,
  CommonsRunnerImagePullSecretFromJSONTyped,
  CommonsRunnerImagePullSecretToJSON
} from './CommonsRunnerImagePullSecret'

/**
 *
 * @export
 * @interface CommonsListRunnerImagePullSecretsOutput
 */
export interface CommonsListRunnerImagePullSecretsOutput {
  /**
   *
   * @type {Array<CommonsRunnerImagePullSecret>}
   * @memberof CommonsListRunnerImagePullSecretsOutput
   */
  runner_image_pull_secrets?: Array<CommonsRunnerImagePullSecret>
}

/**
 * Check if a given object implements the CommonsListRunnerImagePullSecretsOutput interface.
 */
export function instanceOfCommonsListRunnerImagePullSecretsOutput(
  value: object
): value is CommonsListRunnerImagePullSecretsOutput {
  return true
}

export function CommonsListRunnerImagePullSecretsOutputFromJSON(
  json: any
): CommonsListRunnerImagePullSecretsOutput {
  return CommonsListRunnerImagePullSecretsOutputFromJSONTyped(json, false)
}

export function CommonsListRunnerImagePullSecretsOutputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsListRunnerImagePullSecretsOutput {
  if (json == null) {
    return json
  }
  return {
    runner_image_pull_secrets:
      json['runner_image_pull_secrets'] == null
        ? undefined
        : (json['runner_image_pull_secrets'] as Array<any>).map(
            CommonsRunnerImagePullSecretFromJSON
          )
  }
}

export function CommonsListRunnerImagePullSecretsOutputToJSON(
  value?: CommonsListRunnerImagePullSecretsOutput | null
): any {
  if (value == null) {
    return value
  }
  return {
    runner_image_pull_secrets:
      value['runner_image_pull_secrets'] == null
        ? undefined
        : (value['runner_image_pull_secrets'] as Array<any>).map(
            CommonsRunnerImagePullSecretToJSON
          )
  }
}
