/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CommonsRunnerImagePullSecretDockerCredentials } from './CommonsRunnerImagePullSecretDockerCredentials'
import {
  CommonsRunnerImagePullSecretDockerCredentialsFromJSON,
  CommonsRunnerImagePullSecretDockerCredentialsFromJSONTyped,
  CommonsRunnerImagePullSecretDockerCredentialsToJSON
} from './CommonsRunnerImagePullSecretDockerCredentials'
import type { CommonsRunnerImagePullSecretAWS } from './CommonsRunnerImagePullSecretAWS'
import {
  CommonsRunnerImagePullSecretAWSFromJSON,
  CommonsRunnerImagePullSecretAWSFromJSONTyped,
  CommonsRunnerImagePullSecretAWSToJSON
} from './CommonsRunnerImagePullSecretAWS'

/**
 *
 * @export
 * @interface CommonsUpdateRunnerImagePullSecretInput
 */
export interface CommonsUpdateRunnerImagePullSecretInput {
  /**
   *
   * @type {CommonsRunnerImagePullSecretAWS}
   * @memberof CommonsUpdateRunnerImagePullSecretInput
   */
  aws?: CommonsRunnerImagePullSecretAWS
  /**
   *
   * @type {CommonsRunnerImagePullSecretDockerCredentials}
   * @memberof CommonsUpdateRunnerImagePullSecretInput
   */
  docker_credentials?: CommonsRunnerImagePullSecretDockerCredentials
}

/**
 * Check if a given object implements the CommonsUpdateRunnerImagePullSecretInput interface.
 */
export function instanceOfCommonsUpdateRunnerImagePullSecretInput(
  value: object
): value is CommonsUpdateRunnerImagePullSecretInput {
  return true
}

export function CommonsUpdateRunnerImagePullSecretInputFromJSON(
  json: any
): CommonsUpdateRunnerImagePullSecretInput {
  return CommonsUpdateRunnerImagePullSecretInputFromJSONTyped(json, false)
}

export function CommonsUpdateRunnerImagePullSecretInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommonsUpdateRunnerImagePullSecretInput {
  if (json == null) {
    return json
  }
  return {
    aws:
      json['aws'] == null
        ? undefined
        : CommonsRunnerImagePullSecretAWSFromJSON(json['aws']),
    docker_credentials:
      json['docker_credentials'] == null
        ? undefined
        : CommonsRunnerImagePullSecretDockerCredentialsFromJSON(
            json['docker_credentials']
          )
  }
}

export function CommonsUpdateRunnerImagePullSecretInputToJSON(
  value?: CommonsUpdateRunnerImagePullSecretInput | null
): any {
  if (value == null) {
    return value
  }
  return {
    aws: CommonsRunnerImagePullSecretAWSToJSON(value['aws']),
    docker_credentials: CommonsRunnerImagePullSecretDockerCredentialsToJSON(
      value['docker_credentials']
    )
  }
}
