/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TypesGenericSuccessMessage
 */
export interface TypesGenericSuccessMessage {
  /**
   *
   * @type {string}
   * @memberof TypesGenericSuccessMessage
   */
  message?: string
}

/**
 * Check if a given object implements the TypesGenericSuccessMessage interface.
 */
export function instanceOfTypesGenericSuccessMessage(
  value: object
): value is TypesGenericSuccessMessage {
  return true
}

export function TypesGenericSuccessMessageFromJSON(
  json: any
): TypesGenericSuccessMessage {
  return TypesGenericSuccessMessageFromJSONTyped(json, false)
}

export function TypesGenericSuccessMessageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TypesGenericSuccessMessage {
  if (json == null) {
    return json
  }
  return {
    message: json['message'] == null ? undefined : json['message']
  }
}

export function TypesGenericSuccessMessageToJSON(
  value?: TypesGenericSuccessMessage | null
): any {
  if (value == null) {
    return value
  }
  return {
    message: value['message']
  }
}
