/* tslint:disable */
/* eslint-disable */
/**
 * Warp Builds API Docs
 * This is the docs for warp builds api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface WarpBuildAPIError
 */
export interface WarpBuildAPIError {
  /**
   *
   * @type {string}
   * @memberof WarpBuildAPIError
   */
  code?: string
  /**
   *
   * @type {string}
   * @memberof WarpBuildAPIError
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof WarpBuildAPIError
   */
  message?: string
  /**
   *
   * @type {string}
   * @memberof WarpBuildAPIError
   */
  sub_code?: string
  /**
   *
   * @type {string}
   * @memberof WarpBuildAPIError
   */
  sub_message?: string
}

/**
 * Check if a given object implements the WarpBuildAPIError interface.
 */
export function instanceOfWarpBuildAPIError(
  value: object
): value is WarpBuildAPIError {
  return true
}

export function WarpBuildAPIErrorFromJSON(json: any): WarpBuildAPIError {
  return WarpBuildAPIErrorFromJSONTyped(json, false)
}

export function WarpBuildAPIErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WarpBuildAPIError {
  if (json == null) {
    return json
  }
  return {
    code: json['code'] == null ? undefined : json['code'],
    description: json['description'] == null ? undefined : json['description'],
    message: json['message'] == null ? undefined : json['message'],
    sub_code: json['sub_code'] == null ? undefined : json['sub_code'],
    sub_message: json['sub_message'] == null ? undefined : json['sub_message']
  }
}

export function WarpBuildAPIErrorToJSON(value?: WarpBuildAPIError | null): any {
  if (value == null) {
    return value
  }
  return {
    code: value['code'],
    description: value['description'],
    message: value['message'],
    sub_code: value['sub_code'],
    sub_message: value['sub_message']
  }
}
